# Genotyping quantification

Here we will show the scripts and commands used to plot the genotyping results from the single-cell long-read data.

```{r set up, warning = FALSE, message = FALSE}
# Source setup file including all required packages and functions
source("./functions/setup.R")
```

### Load in data

First load in all the data required.
```{r load in data}
# Load in adata object to have consistent cluster info and umap
multiome = schard::h5ad2seurat("./data/multiome_adata_04072025.h5ad")

# Load in barcode matching
dna_barcodes = fread("./data/cellranger_arc_atac.737K-arc-v1.txt.gz", header = FALSE)
rna_barcodes = fread("./data/cellranger_arc_rna.737K-arc-v1.txt.gz", header = FALSE)
matched_barcodes = cbind(dna_barcodes, rna_barcodes)
setnames(matched_barcodes, c("atac_barcode", "cDNA_barcode"))

# Load in genotyping data

# cDNA
vcf_files_cDNA = list.files("./data/cellsnp/cDNA/",
														pattern = "cellSNP.cells.vcf.gz",
														full.names = TRUE, recursive = TRUE)

# DNA
vcf_files_DNA = list.files("./data/cellsnp/DNA/",
													 pattern = "cellSNP.cells.vcf.gz",
													 full.names = TRUE, recursive = TRUE)
```

### Preprocessing

Specify variants and preprocess all data

```{r preprocessing}
# Variant targets
targets = data.table(variants = c("12:112450395", "4:1961074",
                                  "13:28028203", "1:114716126",
                                  "1:114716123", "12:112450406",
                                  "12:25225628", "12:25245347",
                                  "16:28935555", "16:28935556",
                                  "16:28936152"),
                     variant_name = c("PTPN11-A72V", "NSD2-E1099K",
                                      "FLT3-N676K", "NRAS-G12D",
                                      "NRAS-G13D", "PTPN11-E76Q",
                                      "KRAS-C_T", "KRAS-G13D",
                                      "CD19-1_G_A", "CD19-2_T_C",
                                      "CD19-3_G_T"))


# Loop through vcf files and get genotypes
res_cDNA = lapply(vcf_files_cDNA, function(vcf_file) {
  vcf = fread(vcf_file)
  #vcf = vcf[grepl(paste0(targets$variants, collapse = "|"), paste0(vcf$`#CHROM`, ":", vcf$POS)), ]

  # Get the list of sample column names (assuming they start from the 10th column)
  sample_columns = colnames(vcf)[10:ncol(vcf)]

  # Initialize a list to store results
  mut_dt = pblapply(seq_len(nrow(vcf)), function(i) {
    # Extract the current row
    row_data = vcf[i, ..sample_columns]

    # Identify matching sample columns for genotypes '1/1', '0/1', '1/0'
    covered_mut = sample_columns[grepl("0/0", as.character(unlist(row_data)))]
    has_mut = sample_columns[grepl("1/1|0/1|1/0", as.character(unlist(row_data)))]

    dt = lapply(c(covered_mut, has_mut), function(x) {
      data.table(
        sample = x,
        variant_id = paste0(vcf[i, `#CHROM`], ":", vcf[i, POS]),
        genotype = gsub("^([^:]*):.*$", "\\1", vcf[i, ..x]),
        alt_depth = as.numeric(gsub("^([^:]*):([^:]*):.*$", "\\2", vcf[i, ..x])),
        total_depth = as.numeric(gsub("^([^:]*):([^:]*):([^:]*):.*$", "\\3", vcf[i, ..x])))
    }) |> rbindlist()
    return(dt)
  }, cl = 12)
  
  dt = rbindlist(mut_dt)
  dt[, timepoint := gsub(".*cDNA\\/\\/", "", vcf_file)]
  dt[, timepoint := gsub("/cellSNP.*", "", timepoint)]
  return(dt)
})
res_cDNA = rbindlist(res_cDNA)
res_cDNA[, barcode := paste0(sample, "-", timepoint)]
res_cDNA = merge(res_cDNA, targets, by.x = "variant_id", by.y = "variants", all.x = TRUE)

# Loop through vcf files and get genotypes
res_DNA = lapply(vcf_files_DNA, function(vcf_file) {
  vcf = fread(vcf_file)
  #vcf = vcf[grepl(paste0(targets$variants, collapse = "|"), paste0(vcf$`#CHROM`, ":", vcf$POS)), ]

  # Get the list of sample column names (assuming they start from the 10th column)
  sample_columns = colnames(vcf)[10:ncol(vcf)]

  # Initialize a list to store results
  mut_dt = pblapply(seq_len(nrow(vcf)), function(i) {
    # Extract the current row
    row_data = vcf[i, ..sample_columns]

    # Identify matching sample columns for genotypes '1/1', '0/1', '1/0'
    covered_mut = sample_columns[grepl("0/0", as.character(unlist(row_data)))]
    has_mut = sample_columns[grepl("1/1|0/1|1/0", as.character(unlist(row_data)))]

    dt = lapply(c(covered_mut, has_mut), function(x) {
      data.table(
        sample = x,
        variant_id = paste0(vcf[i, `#CHROM`], ":", vcf[i, POS]),
        genotype = gsub("^([^:]*):.*$", "\\1", vcf[i, ..x]),
        alt_depth = as.numeric(gsub("^([^:]*):([^:]*):.*$", "\\2", vcf[i, ..x])),
        total_depth = as.numeric(gsub("^([^:]*):([^:]*):([^:]*):.*$", "\\3", vcf[i, ..x])))
    }) |> rbindlist()
    return(dt)
  }, cl = 12)
  
  dt = rbindlist(mut_dt)
  dt[, timepoint := gsub(".*DNA\\/\\/", "", vcf_file)]
  dt[, timepoint := gsub("/cellSNP.*", "", timepoint)]
  return(dt)
})
res_DNA = rbindlist(res_DNA)
res_DNA = merge(res_DNA, matched_barcodes, by.x = "sample", by.y = "atac_barcode")
res_DNA[, barcode := paste0(cDNA_barcode, "-", timepoint)]
res_DNA = merge(res_DNA, targets, by.x = "variant_id", by.y = "variants", all.x = TRUE)
```

### Plot UMAPs with genotyping results

```{r plot umaps, fig.width = 24, fig.height = 12}

# Get UMAP information
cell_embeddings = data.table(multiome@reductions$Xumap_@cell.embeddings)
cell_embeddings[, sample := rownames(multiome@reductions$Xumap_@cell.embeddings)]

# Merge with genotyping data
dt_cDNA = merge(cell_embeddings, res_cDNA, by.x = "sample", by.y = "barcode", all.x = TRUE)
dt_DNA = merge(cell_embeddings, res_DNA, by.x = "sample", by.y = "barcode", all.x = TRUE)

# Quantification
dt_cDNA[, power := ifelse(total_depth >= 2, "yes", "no")]
dt_DNA[, power := ifelse(total_depth >= 2, "yes", "no")]

# Add presence column
dt_cDNA[, presence := ifelse(genotype %in% c("1/1", "0/1", "1/0") & alt_depth >= 2, "1", "0")]
dt_DNA[, presence := ifelse(genotype %in% c("1/1", "0/1", "1/0") & alt_depth >= 2, "1", "0")]

# Make wide
dt_cDNA_wide = dcast(dt_cDNA, sample + Xumap_1 + Xumap_2 + total_depth + alt_depth ~ variant_name, value.var = "presence")
dt_cDNA = melt(dt_cDNA_wide, id.vars = c("sample", "Xumap_1", "Xumap_2", "total_depth", "alt_depth"),
               variable.name = "variant_name", value.name = "presence")
dt_cDNA[is.na(presence), presence := "0"]
dt_cDNA = dt_cDNA[variant_name %in% targets$variant_name]

dt_DNA_wide = dcast(dt_DNA, sample + Xumap_1 + Xumap_2 + total_depth + alt_depth ~ variant_name, value.var = "presence")
dt_DNA = melt(dt_DNA_wide, id.vars = c("sample", "Xumap_1", "Xumap_2", "total_depth", "alt_depth"),
               variable.name = "variant_name", value.name = "presence")
dt_DNA[is.na(presence), presence := "0"]
dt_DNA = dt_DNA[variant_name %in% targets$variant_name]

# Plot UMAP
umap_cDNA = ggplot() +
  ggrastr::rasterize(geom_point(data = dt_cDNA[presence == "0"], aes(x = Xumap_1, y = Xumap_2), size = .5, color = "#5a5a7c"), dpi = 300) +
  ggrastr::rasterize(geom_point(data = dt_cDNA[presence == "1"], aes(x = Xumap_1, y = Xumap_2), size = .8, color = "red"), dpi = 300) +
  facet_wrap(~variant_name) +
	theme_cowplot() +
	labs(title = "Genotype UMAP cDNA", x = "UMAP 1", y = "UMAP 2", color = "Variant")
	
umap_DNA = ggplot(dt_DNA, aes(x = Xumap_1, y = Xumap_2, color = presence)) +
  ggrastr::rasterize(geom_point(data = dt_cDNA[presence == "0"], aes(x = Xumap_1, y = Xumap_2), size = .5, color = "#5a5a7c"), dpi = 300) +
  ggrastr::rasterize(geom_point(data = dt_cDNA[presence == "1"], aes(x = Xumap_1, y = Xumap_2), size = .8, color = "red"), dpi = 300) +
  facet_wrap(~variant_name) +
	theme_cowplot() +
	labs(title = "Genotype UMAP DNA", x = "UMAP 1", y = "UMAP 2", color = "Variant")

umap_DNA + umap_cDNA
```